using System.Text.Json;
using MBW.Tools.GhStandardContent.Core;

namespace MBW.Tools.GhStandardContent.Configuration;

internal sealed class ConfigurationLoader
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        AllowTrailingCommas = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        PropertyNameCaseInsensitive = true
    };

    public async Task<(LoadedConfiguration? Configuration, IReadOnlyList<ValidationDiagnostic> Diagnostics)> LoadAsync(
        string path, CancellationToken cancellationToken)
    {
        List<ValidationDiagnostic> diagnostics = [];
        string fullPath;
        try
        {
            fullPath = Path.GetFullPath(path);
        }
        catch (Exception exception)
        {
            diagnostics.Add(new("config.path", exception.Message, path));
            return (null, diagnostics);
        }

        if (!File.Exists(fullPath))
        {
            diagnostics.Add(new("config.notFound", "Configuration file does not exist.", fullPath));
            return (null, diagnostics);
        }

        RepositoryConfigurationFile? document;
        try
        {
            byte[] json = await File.ReadAllBytesAsync(fullPath, cancellationToken);
            using JsonDocument syntax = JsonDocument.Parse(json, new JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling = JsonCommentHandling.Skip
            });
            if (syntax.RootElement.ValueKind != JsonValueKind.Object)
            {
                diagnostics.Add(new("config.invalidRoot", "Configuration root must be a JSON object.", fullPath));
                return (null, diagnostics);
            }

            HashSet<string> allowedProperties = new(["$schema", "content", "repositories"], StringComparer.OrdinalIgnoreCase);
            foreach (JsonProperty property in syntax.RootElement.EnumerateObject())
            {
                if (!allowedProperties.Contains(property.Name))
                    diagnostics.Add(new("config.unknownProperty", $"Unknown root property '{property.Name}'.", property.Name));
            }

            document = JsonSerializer.Deserialize<RepositoryConfigurationFile>(json, JsonOptions);
        }
        catch (JsonException exception)
        {
            diagnostics.Add(new("config.invalidJson", exception.Message, fullPath));
            return (null, diagnostics);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            diagnostics.Add(new("config.unreadable", exception.Message, fullPath));
            return (null, diagnostics);
        }

        if (document is null)
        {
            diagnostics.Add(new("config.empty", "Configuration file is empty.", fullPath));
            return (null, diagnostics);
        }

        if (document.Content is null)
            diagnostics.Add(new("config.contentRequired", "The 'content' object is required.", fullPath));
        if (document.Repositories is null)
            diagnostics.Add(new("config.repositoriesRequired", "The 'repositories' object is required.", fullPath));
        if (diagnostics.Count > 0)
            return (null, diagnostics);

        string directory = Path.GetDirectoryName(fullPath) ?? Directory.GetCurrentDirectory();
        Dictionary<string, IReadOnlyDictionary<string, SourceFile>> profiles = new(StringComparer.Ordinal);

        foreach ((string profileName, Dictionary<string, string>? entries) in document.Content!)
        {
            if (string.IsNullOrWhiteSpace(profileName))
            {
                diagnostics.Add(new("profile.emptyName", "Profile names cannot be empty.", "content"));
                continue;
            }

            if (entries is null)
            {
                diagnostics.Add(new("profile.invalid", $"Profile '{profileName}' must be an object.", $"content.{profileName}"));
                continue;
            }

            Dictionary<string, SourceFile> normalizedEntries = new(StringComparer.Ordinal);
            foreach ((string target, string? source) in entries)
            {
                if (!ManagedPath.TryNormalize(target, out string normalizedTarget, out string error))
                {
                    diagnostics.Add(new("path.invalid", error, $"content.{profileName}.{target}"));
                    continue;
                }

                if (normalizedTarget.Equals(ContentPlanner.MetadataPath, StringComparison.Ordinal))
                {
                    diagnostics.Add(new("path.reserved", $"'{ContentPlanner.MetadataPath}' is generated by the tool and cannot be configured.",
                        $"content.{profileName}.{target}"));
                    continue;
                }

                if (string.IsNullOrWhiteSpace(source))
                {
                    diagnostics.Add(new("source.empty", "Source paths cannot be empty.", $"content.{profileName}.{target}"));
                    continue;
                }

                string sourcePath;
                try
                {
                    sourcePath = Path.GetFullPath(Path.Combine(directory, source));
                }
                catch (Exception exception) when (exception is ArgumentException or NotSupportedException or PathTooLongException)
                {
                    diagnostics.Add(new("source.invalidPath", exception.Message, $"content.{profileName}.{target}"));
                    continue;
                }

                if (!File.Exists(sourcePath))
                {
                    diagnostics.Add(new("source.notFound", $"Source file '{source}' does not exist.",
                        $"content.{profileName}.{target}"));
                    continue;
                }

                byte[] content;
                try
                {
                    content = TextContent.Normalize(await File.ReadAllBytesAsync(sourcePath, cancellationToken));
                }
                catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
                {
                    diagnostics.Add(new("source.unreadable", exception.Message, $"content.{profileName}.{target}"));
                    continue;
                }

                if (!normalizedEntries.TryAdd(normalizedTarget, new SourceFile(normalizedTarget, sourcePath, content)))
                    diagnostics.Add(new("path.duplicate", $"Target '{normalizedTarget}' is duplicated in profile '{profileName}'.",
                        $"content.{profileName}"));
            }

            profiles[profileName] = normalizedEntries;
        }

        Dictionary<string, IReadOnlyDictionary<string, bool>> repositories = new(StringComparer.OrdinalIgnoreCase);
        foreach ((string repository, Dictionary<string, bool>? selectedProfiles) in document.Repositories!)
        {
            if (!IsRepositoryName(repository))
            {
                diagnostics.Add(new("repository.invalidName", "Repository names must use the exact 'owner/name' form.",
                    $"repositories.{repository}"));
                continue;
            }

            if (selectedProfiles is null)
            {
                diagnostics.Add(new("repository.invalid", $"Repository '{repository}' must be an object.",
                    $"repositories.{repository}"));
                continue;
            }

            foreach (string profile in selectedProfiles.Keys)
            {
                if (!profiles.ContainsKey(profile))
                    diagnostics.Add(new("repository.unknownProfile", $"Repository '{repository}' references unknown profile '{profile}'.",
                        $"repositories.{repository}.{profile}"));
            }

            Dictionary<string, string> targets = new(StringComparer.Ordinal);
            foreach (string profile in selectedProfiles.Where(item => item.Value).Select(item => item.Key))
            {
                if (!profiles.TryGetValue(profile, out IReadOnlyDictionary<string, SourceFile>? files))
                    continue;

                foreach (string target in files.Keys)
                {
                    if (!targets.TryAdd(target, profile))
                        diagnostics.Add(new("repository.duplicateTarget",
                            $"Profiles '{targets[target]}' and '{profile}' both define target '{target}' for '{repository}'.",
                            $"repositories.{repository}"));
                }
            }

            if (!repositories.TryAdd(repository, new Dictionary<string, bool>(selectedProfiles, StringComparer.Ordinal)))
                diagnostics.Add(new("repository.duplicate", $"Repository '{repository}' is duplicated with different casing.",
                    $"repositories.{repository}"));
        }

        LoadedConfiguration configuration = new(fullPath, directory, profiles, repositories);
        return (configuration, diagnostics);
    }

    public Task<DesiredRepository> BuildDesiredAsync(
        LoadedConfiguration configuration, string repository, string? metaReference, CancellationToken cancellationToken)
    {
        IReadOnlyDictionary<string, bool> repositoryConfiguration = configuration.Repositories[repository];
        string[] profiles = repositoryConfiguration
            .Where(item => item.Value)
            .Select(item => item.Key)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        Dictionary<string, byte[]> files = new(StringComparer.Ordinal);
        foreach (string profile in profiles)
        {
            foreach (SourceFile source in configuration.Profiles[profile].Values)
            {
                cancellationToken.ThrowIfCancellationRequested();
                files.Add(source.TargetPath, source.Content);
            }
        }

        return Task.FromResult(new DesiredRepository(repository, profiles, files, metaReference));
    }

    private static bool IsRepositoryName(string value)
    {
        string[] parts = value.Split('/');
        return parts.Length == 2 && parts.All(part => !string.IsNullOrWhiteSpace(part) &&
                                                     part.All(character => !char.IsWhiteSpace(character)));
    }
}
